INSERT INFO zvjj1_authors (`name`)
VALUES
("ankama"),
("delcourt"),
("flammarion"),
("glénat"),
("hachette"),
("kazé / vaz"),
("panini"),
("univers poche"),
("12bis"),
("akata"),
("Black Box Éditions"),
("Booken Manga"),
("Boy’s Love – IDP"),
("Cambourakis"),
("Clair de lune"),
("Cornélius"),
("Doki Doki"),
("Editions FLBLB"),
("Editions H"),
("Éditions Matière"),
("Editions Philippe Picquier"),
("Ego comme X"),
("H&O Editions"),
("IMHO"),
("Isan Manga"),
("Ki-oon"),
("Komikku Éditions"),
("Kwari"),
("Le Lézard Noir (P’tit Lézard)"),
("Les Éditions Fei"),
("Milady Graphic"),
("Paquet (Bao)"),
("Sarbacane"),
("Taifu Comics (Ototo)"),
("Vertige Graphic"),
("Akileos (Tengai)"),
("Albin Michel"),
("Dark Horse Comics"),
("Digiclub"),
("Dynamic Visions / Dybex"),
("Éditions Atomic Club"),
("Editions de Tournon (Carabas, Kami, Semic, Yômâ)"),
("Gekko"),
("Harlequin Manga"),
("Katsumi"),
("J’ai Lu Manga"),
("Kraken"),
("L’écho des savannes"),
("L’écho des savannes"),
("Les éditions Muffins"),
("Les Humanoïdes associés"),
("Manga Player Collection"),
("Milan"),
("Muteki"),
("Presse de la cité"),
("Samji"),
("Samouraï Editions"),
("SeeBD"),
("Seuil"),
("Toki"),
("Vegetal Manga"),
("Vegetal Shuppan"),
("Wetta Comics"),
("Xiao Pan");